### ISSUE TITLE
Exception when cookie value contains an equals character

### ISSUE THREAD

**Issue by d6y** [Spinoco/protocol#3]
As [discussed on Gitter](https://gitter.im/fs2-http/Lobby?at=58d05591590d72c864eae8fe), cookie values can contain equals signs. This leads to a runtime exception.  For example, using the echo service in the fs2-http readme:

```
$ http :9090/echo 'Cookie:name=value=1'
HTTP/1.1 400 Bad Request
```

...results in:

```
[ERROR] java.lang.Throwable: Decoding of the request header failed: 
    Headers/Cookie: Expected tuple, got List(Right(name), Right(value), Right(1))
[ERROR] 	at spinoco.fs2.http.HttpRequest$.$anonfun$fromStream$2(HttpRequestOrResponse.scala:218)
[ERROR] 	at fs2.Stream.$anonfun$flatMap$1(Stream.scala:148)
...
```

A "real world" cookie that has this structure is Google Analytics `__utmz`.

**Comment by d6y** [comment]
WIP Fix: https://github.com/Spinoco/protocol/compare/master...d6y:equals-in-cookie-value
